name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Formatting
        run: cargo fmt -- --check

      - name: Linting
        run: cargo clippy -- -D warnings -W clippy::pedantic

      - name: Tests
        run: cargo test
